### ISSUE TITLE
Upgrade to v3 issues 

### ISSUE THREAD

**Issue by eviweb** [wooclap/moodle-mod_wooclap#13]
Hi,
I ran into the following issue during the upgrade to `v2021062500`.
![wooclap-2021062500-upgrade-issue](https://user-images.githubusercontent.com/1310382/135586954-ff4d82fa-f24f-4829-bd72-79338cabc6ed.png)
Then another error concerning the `get_isotime()` function from `./lib.php` occured.
The problem comes from that the requested files are not imported in `./db/upgrade.php`.
I will provide a quick fix.
Regarding classes at the top level of the `./classes` folder, IMHO you should consider to set them under the `mod_wooclap` namespace, in order to benefit from the class autoloader of Moodle.
Best regards

**Comment by mehira-wooclap** [comment]
The next release will fix the issue.

**Comment by dfdeagle47** [comment]
@eviweb New version published [here](https://moodle.org/plugins/mod_wooclap/versions) and [here](https://moodle.org/plugins/mod_wooclap/2021122000/25693) which adds the correct imports.
