### ISSUE TITLE
Lesson import questions function and Wooclap activity

### ISSUE THREAD

**Issue by forobliot** [wooclap/moodle-mod_wooclap#16]
Hello, 
I am contacting you in order to report an issue about the use of Wooclap activities and Lesson Activities in the same Moodle course. We noticed that the function "Lesson mod import questions" of a Lesson acitvity does not work if there is a wooclap activity in the same course. The issue seems to be related to the wooclap lib.php which includes the question/format.php file. Is it essential for the Wooclap Moodle plugin?

step to reproduce the problem:

- add a wooclap activity to the course
- add a lesson activity
- open the lesson and start importing questions

**Comment by Wanbonnet** [comment]
Hello @forobliot, 

Thank you for reporting this issue. We'll have a look into it, and get back to you when we have an update to provide.

**Comment by manzan46** [comment]
@forobliot Sorry for the delay on this one, we think we found the issue and it's indeed link to this similar fix done on Moodle side https://github.com/moodle/moodle/blob/556208417deb47ccea80d00849aae6fb4d47f228/question/format/xml/format.php#L29 where for some reason two file `format.php` and the `mod/lesson.format.php`are declaring the same function. 

We will release a new version of the plugin after having done more test and keep you posted, 🤞🏻  before end of week

**Comment by manzan46** [comment]
👋🏻  @forobliot  

We fixed the issue, could you please ask  update to the last Moodle Wooclap plugin which is the 2023030900 and then retry.

Let us know if all good and sorry for the inconvenience.

**Comment by forobliot** [comment]
I have just updated the plugin and now I am able to import questions into lesson-type activities, 
thanks for fixing the plugin's code!

**Comment by manzan46** [comment]
@forobliot  thanks for quick feedback and reporting the issue in first place. 🙏🏻
