### ISSUE TITLE
Wooclap activity has no "Grade" settings

### ISSUE THREAD

**Issue by lucaboesch** [wooclap/moodle-mod_wooclap#17]
When setting up a Wooclap activity, it is neither possible to add it to a gradebook category nor to assign it a different score other than points: 100
Due to this fact, independently on how you set up your gradebook it is not possible to 'hide' ungraded Wooclap activities in a (e.g.) "ungraded activities" gradebook category and it is not possible to grant it 0 points, what you would expect from an ungraded activity.

Update: It is possible to place it in a gradebook category but by being able to do this in a "Grade" category in the activity settings would be more user friendly.

**Comment by hribeir0** [comment]
We've also been struggling with this. The maximum grade is always the one defined per default on the whole site.. You are not able to change this since this setting in the gradebook is managed by the activity setting, which doesn't exist in mod_wooclap.
So as workaround we need a new gradebook category for each wooclap what makes thing unmanageable

**Comment by lucaboesch** [comment]
I wonder whether this would be fixed by #21.

**Comment by marco-verbeek** [comment]
Hey everyone 👋🏼 

We've recently deployed a new version of the plugin, which includes a feature regarding activity grading.

Activities now have the following settings:
![Screenshot 2023-12-18 at 15 55 40](https://github.com/wooclap/moodle-mod_wooclap/assets/56871713/dd9643a3-5232-4144-abf5-e98a14a89db3)

You can find out all about it in this PR: https://github.com/wooclap/moodle-mod_wooclap/pull/29

I'll let you close this issue if this is what you've wanted, if it's not, let's discuss what is missing! 

As always, thank you for your contribution! 🙏🏼  
Marco
