### ISSUE TITLE
Enable anonymous voting

### ISSUE THREAD

**Issue by zabellemotte** [wooclap/moodle-mod_wooclap#18]
The Wooclap moodle integration plugin disables the possibility to make vote anonymous. It seems to be an important pedagogical restriction because anonymity has been proven to be important for student engagement has it can be read in this interesting meta-analysis :
https://www.sciencedirect.com/science/article/pii/S0360131520300956

Wooclap Moodle integration seems much more interresting if anonymous vote is enabled, because Moodle does not allow teachers to make quiz answers anonymous.

**Comment by zabellemotte** [comment]
This phd thesis offers also lightnings about interest of anonymous voting specifically for students with low level of knowledge.
See page 101 to see an summary table of the experimentation results :
https://theses.hal.science/tel-01344635

**Comment by marco-verbeek** [comment]
👋🏼 Hello @zabellemotte,

Wooclap allows teachers to disable the authentication requirement, which then allows anonymous participants. Events created with the Moodle plugin require authentication by default, but teachers can easily toggling this requirement off.

The option can be found in the event settings, as shown in this screenshot:
![Screenshot 2024-11-28 at 10 17 17](https://github.com/user-attachments/assets/48ead490-e59e-4e61-8b37-b2c1b9daf972)

Thank you,
Marco
