### ISSUE TITLE
Support backup/restore

### ISSUE THREAD

**Issue by lucaboesch** [wooclap/moodle-mod_wooclap#2]
I don't think wooclap does properly support backup and restore in Moodle.
So, if you copy a course, the Wooclaps are gone for example.
I think the team should work on that, hints can be found in https://docs.moodle.org/dev/Backup_API and https://docs.moodle.org/dev/Restore_API

Best,
Luca

**Comment by dfdeagle47** [comment]
Dear @lucaboesch, we've worked on supporting this feature since your last message, and we're currently testing this feature with a few universities to make sure everything is working properly.

Do you already use our Moodle plugin and would like to be part of this testing phase?

/cc @tchapeaux @Wanbonnet

**Comment by lucaboesch** [comment]
Hi Jonathan,

Yes this would be great!

Best,

Luca

**Comment by ndunand** [comment]
Hi @dfdeagle47 ,

We here at unil.ch use the plugin in our Moodle and just noticed (😕) this. Therefore we would like to be part of the testing phase.

Thanks @lucaboesch for noticing this before me 😊

**Comment by jrm-unamur** [comment]
Hi,
If that can help, we can test it too at Univeristy of Namur

**Comment by tchapeaux** [comment]
Hi @lucaboesch @ndunand @jrm-unamur ,

We just released a new version to enable the backup/restore feature:
https://github.com/wooclap/moodle-mod_wooclap/commit/1b31bbecbc9e710321e00a83d182406b6ec81c17

You should be able to perform the update from your Moodle platform and from the [Moodle plugin repository](https://moodle.org/plugins/mod_wooclap).

Thanks for bringing this to our attention!
