### ISSUE TITLE
What is the role of auth_wooflash.php

### ISSUE THREAD

**Issue by mudrd8mz** [wooclap/moodle-mod_wooclap#3]
I've been experimenting a bit and I have some concern related to the functionality of the auth_wooflash.php script.

What is the purpose of it and how is it supposed to be called? From what I can see, it can be eventually abused for providing a malicious "login" link to a user who would then authenticate to their moodle and then be redirected to a defined URL.

**Comment by Mickael-van-der-Beek** [comment]
Hello @mudrd8mz,

Just wanted to double check if I understood your report correctly.
Are you meaning to say a malicious Moodle admin could make it possible to create a malicious redirect link?
From what I can read in code, it will take the configured Apache `Host` as hostname value if I'm not mistaken.
cf: https://github.com/wooclap/moodle-mod_wooflash/blob/master/auth_wooflash.php#L58

**Comment by tchapeaux** [comment]
Indeed, we might have an Open Redirect vulnerability in this case. Thanks for notifying us.

We should validate the redirect URL against the baseurl plugin settings.

**Comment by dfdeagle47** [comment]
Fixed in the new release: [here](https://moodle.org/plugins/mod_wooclap/versions) and [here](https://moodle.org/plugins/mod_wooclap/2021122000/25693).
