### ISSUE TITLE
question/export_form.php can not be used any more in Moodle ≥ 4.4

### ISSUE THREAD

**Issue by lucaboesch** [wooclap/moodle-mod_wooclap#35]
From Moodle ≥ 4.4 on, the file does not exist any more, see question/upgrade.txt.

**Comment by izendegi** [comment]
Hi,

We've seen this same issue when testing Moodle 4.4 and it breaks all the site, so it's a severe issue and it should be to make the plugin work with Moodle 4.4.

**Comment by Wanbonnet** [comment]
Hello @lucaboesch @izendegi ,
Thank you for reporting the issue. We'll look into it, and I'll come back to you when we have been able to fix the issue.

**Comment by izendegi** [comment]
I've realized that the plugin is marked as compatible with Moodle 4.4 on the Moodle plugin database, I think it would be recommendable to remove that flag until this issue gets fixed.

**Comment by marco-verbeek** [comment]
Thank you for letting us know; we have updated the plugin to show incompatibility with 4.4 (for now!).

We'll let you know as soon as we have more information regarding a fix for 4.4.

**Comment by gemguardian** [comment]
for clarification the debug notification 

![image](https://github.com/wooclap/moodle-mod_wooclap/assets/16559999/8ec77a44-9ee1-49f7-a081-43f5c07b7014)

**Comment by marco-verbeek** [comment]
Thank you for the screenshot, @gemguardian 🙏🏼 

We're working on a fix and we'll let you know as soon as it's available!

**Comment by marco-verbeek** [comment]
👋🏼 hey everyone!

We've released [a new version](https://moodle.org/plugins/mod_wooclap/2024052700/32224) of the plugin that aims at fixing this issue. 
Do let me know if there's anything else we can assist with.

Thank your for your help 🚀 
Marco
