### ISSUE TITLE
Error after update to 2024041900

### ISSUE THREAD

**Issue by jaume77** [wooclap/moodle-mod_wooclap#39]
Hi!

After updating the Wooclap module, from version 2024032800 to version 2024041900, when trying to create or edit a Wooclap activity this error appears:

Fatal error: Declaration of mod_wooclap_mod_form::add_completiongrade_rules() must be compatible with moodleform_mod::add_completiongrade_rules(): array in /home/apsi/moodle/2024-25/web/mod/wooclap/mod_form.php on line 212

Moodle version : 4.3.2

Thanks!
Jaume R.

**Comment by throskam-wooclap** [comment]
Hey !

Thanks for reporting this issue, we have made a fix yesterday in the afternoon.
You can update to the latest version **2024042200** and try again.

For context, the issue cames from a fix for older Moodle version which broke the newer Moodle version.
This last version fixes it but we had to drop the support for versions below 3.4.

**Comment by jaume77** [comment]
Thanks!

Updated and it works again. 👍

Greetings
Jaume R.
