### ISSUE TITLE
Activity completion conditions are not manageable

### ISSUE THREAD

**Issue by chiaravicere** [wooclap/moodle-mod_wooclap#4]
Hello, in the completion option of the Wooclap activity there is the option "Wooclap custom completion - Completion state updated only by Wooclap". 
If you switch off this and save, and return to the settings, it re-enables itself.
I noticed that, if the student grade is less than 50%, the activity does not show as completed. Is there a whay to change this value?

**Comment by chiaravicere** [comment]
Screenshot of interested settings in Moodle activity: https://tinyurl.com/y2pqv4ue

How to reproduce the issue:

1. Switch off the "Wooclap custom completion" option, then save
2. Re-open settings and see that the option is turned on again

Expected behaviour:

- Switching the option off, it should remain off
-The above option "Require grade" should have the declared effect (when the student obtains a grade, even if 0, the activity should be marked as completed).

Feature request:

- The teacher should be able to set a minimum grade from which the activity will be marked as completed.

**Comment by tchapeaux** [comment]
Hello,

Thanks for your request and sorry for the late reply.

Indeed this is not supported by our plugin at the moment. Can you give us more context on why this would be helpful to you?

**Comment by chiaravicere** [comment]
Hello,
if a teacher uses the activity completion for his course, it may have the following aims:
- let the teacher check wich students completed the course activities;
- let the student check his status in the course (he knows wich activities he has completed and wich not);
- show the student some activities only when he completes some other activities, in order to create a sequenciality.

As a teacher, I may want to set one among these conditions to consider completed a Wooclap activity (this is how the activity completion in Moodle usually works):
- I want the student just to open the activity once;
- I want the student to attempt all the questions (so I want him to receive a grade, but I don't mind about which grade);
- I want the student to pass a minimum grade I chose (e.g. 70% of total possible score).

**Comment by tchapeaux** [comment]
Thanks for the extra context!

This feature is not on our internal product roadmap at the moment, and currently we don't have many request for it, so it will not be prioritized immediately.

We would be happy to review and merge a PR about this feature if someone has the dev time for it.

Looking at your use case, it seems that [Wooflash](www.wooflash.com) might interest you. This is another of our product where you can create asynchronous quizzes and integrate them in a Moodle course as well. It is possible to start a free pilot phase here:
https://www.wooflash.com/en/start-a-pilot-phase

**Comment by chiaravicere** [comment]
We tried Wooflash as well, but I remember it had the same incompatibilities as a Moodle module. However for now we decided to go deep with Wooclap instead.

**Comment by gilhoo** [comment]
Hello !
I tried wooclap into Moodle this week and this plugin is really great !
Same request as Chiara for me... I would love to have some control on how the completion of this activity is managed !

**Comment by Kemmotar83** [comment]
Hi, any updates on this issue? It would be very appreciated an enhancement on completion feature. 

Giorgio

**Comment by Wanbonnet** [comment]
@gilhoo @Kemmotar83 thank you for your requests (and sorry @gilhoo for the late answer). 

I am currently trying to better understand this issue. Can you tell us more precisely what you intend to do with more control on the completion? Based on which criteria would you like to define the completion, and why?

Thanks in advance!

**Comment by Kemmotar83** [comment]
Hi @Wanbonnet ,

for example, the "more control" could be having the possibility to define a minimum percentage of correct answers (or grade) to have the activity completed.
Often teachers would like to use completion to track participation, and participants to a Wooclap session could also answer wrongly to questions. It's the same concept of quiz's passing grade, where completion is not only answering correctly to all questions.

Giorgio

**Comment by hribeir0** [comment]
+1 
If needed we can schedule a call to discuss this with someone from wooclap

**Comment by Wanbonnet** [comment]
Thanks a lot for your answers @Kemmotar83 and @hribeir0 !

This feature is not on our internal product roadmap at the moment, but I will make sure we come back to you when it is.

Of course we would be happy to review and merge a PR about this feature if someone has the dev time for it.

**Comment by Wanbonnet** [comment]
Hello @chiaravicere @gilhoo @Kemmotar83 @hribeir0,
We have been able to fix this issue, the completion of a Wooclap activity now works the following way:
- If the "Wooclap custom completion" criteria is checked: the activity will be marked as completed when the participant has interacted with at least one Wooclap question (right or wrong answers)
- If other completion criteria are checked (specific grade or something else), the Wooclap custom completion won't apply

Thank you for reporting the issue, and please keep providing us feedback.
