### ISSUE TITLE
bug install on moodle 4.4

### ISSUE THREAD

**Issue by labretagne** [wooclap/moodle-mod_wooclap#41]
When i try to install wooclap on my 4.4 moodle, it doesn't work with this error log: 
wooclap Exception : Failed opening required '[dirroot]/question/export_form.php' (include_path='[dirroot]/lib/pear:.:/usr/share/php')
In the moodle 4.4 question directory, there is no file named 'export_form.php'

**Comment by lucaboesch** [comment]
This duplicates #35.

**Comment by marco-verbeek** [comment]
Closing as this is a duplicate. @labretagne we have just released a new version that should fix this issue.
You can find the version that contains the fix [here](https://moodle.org/plugins/mod_wooclap/2024052700/32224).

Thank you for letting us know of this issue 🚀 
Marco
