### ISSUE TITLE
Cookie consent banner every time

### ISSUE THREAD

**Issue by chiaravicere** [wooclap/moodle-mod_wooclap#5]
When clicking on a Wooclap activity that opens a new wooclap tab, a blocking banner appears (cookie banner consent). It should be appearing only at first access, otherwise it is really annoying (when opening the same activity often in a day, you have to close it every time, as it cannot remember your choice).

Request:

- Remember the user consent for cookies for a long time;

Or, if not possible:

- Make the cookie consent a non-blocking banner (let the user work anyway).

**Comment by dfdeagle47** [comment]
@chiaravicere

We're aware of this issue and are looking at fixing this behaviour. It will most likely not need an update to the Moodle plugin as the fix will normally be an update to the web app instead.

We'll keep you updated once this is fixed.

**Comment by dfdeagle47** [comment]
@chiaravicere

We have made a change which should hopefully resolve this issue. Could you check again if this is still an issue (you might have to refresh the page)?

If that's the case, could you send us an email at info [at] wooclap.com with a video of the issue, so we can better investigate it?

**Comment by chiaravicere** [comment]
Today I had to close the banner only at the first access :)
