### ISSUE TITLE
Update error from 2020102900 (on moodle 3.5) to 2021062500 (on moodle 3.9)

### ISSUE THREAD

**Issue by Gael-Mifsud** [wooclap/moodle-mod_wooclap#9]
Hello,

On a test platform we upgraded Moodle 3.5.17 to 3.9.7.
We have to update Wooclap from version 2020102900 to the last (2021062500) but we encountered this error : 
`Could not perform Step 1 of the V3 Upgrade`
`Error code: error-couldnotperformv3upgradestep1`
![Wooclap_update_error_7-7-2021](https://user-images.githubusercontent.com/2854045/124785937-94f9c100-df47-11eb-8c22-40775cda345b.jpeg)

We hope you can help on this matter.

Thanks.

**Comment by Gael-Mifsud** [comment]
Note : We use PHP 7.4 for Modole 3.9.

But, we also encountered the same error when updating Wooclap on Moodle 3.5 (PHP 7.2)

Thanks.

**Comment by tchapeaux** [comment]
Hello @Gael-Mifsud , thanks for reaching us with this issue.

I see several attempt today to perform the upgrade without specifying an access key. The Wooclap plugin requires an access key to work, including for the upgrade. Did you specify it in your plugin settings?

This access key should have been provided to you as part of your subscription. If you use a production key, make sure the production data is present on the Moodle platform as well. We can also provide you with a temporary key for your test.

**Comment by Gael-Mifsud** [comment]
Thank you very much.

We used the access key and it worked !

I will close this bug report.

**Comment by dfdeagle47** [comment]
@Gael-Mifsud 

FYI we've addressed this issue in the new release [here](https://github.com/wooclap/moodle-mod_wooclap/releases/tag/2021122000) and [here](https://moodle.org/plugins/mod_wooclap/2021122000/25693). You should now be able to upgrade without the keys, and the migration can be triggered via a CLI script.

For the new release, it shouldn't be necessary to re-trigger this script if you're already on 2021062500 before upgrading the Moodle plugin, but we'll use this process for newer releases if a migration is needed to avoid any issues when upgrading.

Thank you for providing this feedback!
